# Generated by Django 4.2.6 on 2023-10-22 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_art', models.CharField(max_length=50)),
                ('name_art', models.CharField(max_length=50)),
                ('price_art', models.FloatField()),
                ('stock_art', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=1)),
                ('tot_amount', models.PositiveIntegerField(default=0)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.articulo')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.cliente')),
            ],
        ),
    ]
